services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sso_db
    ports:
      - "3306:3306"
    networks:
      - sso-net

  springboot:
    build:
      context: .  # Apunta al directorio actual
    container_name: springboot_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sso_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - sso-net
    entrypoint: ["sh", "-c", "echo 'Esperando a MySQL...' && sleep 20 && java -jar app.jar"]

  react:
    build:
      context: ../../../Frontend/sso-context  # Asegúrate de que esta ruta sea correcta
    container_name: react_container
    ports:
      - "3000:80"
    networks:
      - sso-net

networks:
  sso-net:
